Rev4Labs/storefront

.prettierrc
package.json
server/api/products.js
server/app.js
server/db/Product.js
server/db/User.js
server/db/conn.js
server/db/index.js

config tweaks: db name, .prettierrc file, connection string
complete Product data model
add CRUD routes for /api/products/:id and all products
add requireAdmin middleware function for protected routes
revise seed script for new product model

chore (back-end): product data model & api routes

---

server/api/auth.js

Added /api/auth/signup route for new user.  Finds or creates, returns JWT.  Tested.

chore(back-end): auth route for signing up

---

server/api/users.js
server/app.js

Added protected CRUD routes for user (i.e. profile) with admin access as well.

chore(back-end): User CRUD/Admin Routes

---

server/api/products.js
server/api/reviews.js
server/app.js
server/db/Review.js
server/db/index.js

Add data model and table for product reviews.
Updated routes to return reviews array with product
Added route for creating/updating review
Added reviews to seed file

chore(back-end): Prod Review Data Model and Routes

---

server/api/orders.js
server/db/index.js

chore(back-end): Order Admin Routes

---

package-lock.json
package.json
server/db/LineItem.js
server/db/Product.js
server/db/Review.js
src/Components/ProductAll.js
src/Components/ProductCatalogItemCard.js
src/Components/ProductReviewStars.js
src/Components/ProductSingle.js
static/styles.css

Add hooks to Review data model for updating rating and reviewCount fields in Product table
Create star rating component
Add star rating to catalog and single product views 
Abstract product card from product catalog component

Product reviews component

---

package-lock.json
package.json
server/db/Product.js
server/db/seed.js
src/Components/Pagination.js
src/Components/ProductAll.js

Add pagination component & integrate into catalog
Add product filter thru query string to catalog
Add filter buttons to catalog
Change master data for categories to lower case

Product catalog pagination

---

src/Components/Navbar.js
src/Components/ProductAll.js
src/Components/Search.js

Completed Product Search
Abstracted search form from navbar into separate component and integrated new component into navbar
Revised Product Catalog view to apply search filter
Revised active state for product catalog filter buttons when search is applied
Revised URL to represent search/filter criteria for proper navigation history

feat(front-end): Product Search Complete

---

server/api/orders.js
server/api/reviews.js
src/Components/App.js
src/Components/ProductAll.js
src/Components/ProductFeaturedItems.js
src/Components/ProductLanding.js
src/Components/ProductReviewCreate.js
src/Components/ProductSingle.js
src/store/productAll.js
src/store/productSingle.js

// Five star component for rating/reviewing a product
// Intended to be used in user order history, but can be embedded anywhere, just needs productId as a prop
// Requires user to be logged in 
// Made edit to order API route in line with code review feedback
// Added thunk to refresh single product already on state
// Added thunk to refresh all products without showing "isLoading Spinner"  - this is for unobtrusive refreshing, does not replace "set products"

feat(front-end): Create Review Component

---

src/Components/Login.js

Align style with other site modals
Change behavior of back button to go to prior page as opposed to home.

feat(front-end): Login Style Tweaks

---

src/store/index.js

added redux dev tools

---

src/Components/Cart.js
src/Components/CheckOutModal.js
src/Components/Payment.js
src/store/cart.js

added login to Check out

---

package-lock.json
server/app.js
server/db/seed.js
src/Components/OrderHistory.js
src/Components/OrderLine.js
src/Components/OrderSingle.js
src/Components/ProductReviewCreate.js
src/Components/User.js
src/store/ordersSingleUser.js

// Table-ize order history
// Refactor "create review" star rating with additional lifecycle method to fix not-updating bug on duplicate items
// Add resetUserOrders thunk to "quietly" update components
// Replace user profile history modal with link to this history component.

feat(full-stack): order history w/ reviews

---

src/Components/CartIndicator.js
src/Components/Navbar.js
src/store/cart.js

added item number to cart in nav bar

added indicator to cart

---

package-lock.json
src/Components/CartIndicator.js
src/Components/Navbar.js
src/Components/Search.js
src/store/cart.js
static/styles.css

// Add Cart-Icon Button w/ # cart items
// Change counting algo to sum up all line item quantities
// Made Profile link only show when user is logged in
// Centered all navbar contents vertically
// Always show cart icon, even in collapsed view

feat(front-end) - Navbar Cart Button

---

server/api/orders.js
server/db/User.js
src/Components/Cart.js
src/Components/CheckOutModal.js
src/store/cart.js

fixed quatity bugs
fixed non login
fix remove
added more numbers for quatity selection

Cart-clean-up

---

server/api/email.js
src/Components/App.js
src/Components/CheckOutModal.js
src/Components/ThankYou.js

// Add redirect to checkout modal upon order placement
// Add withRouter utiltiy to checkout modal
// Add /thankyou route
// Add thankyou component with modal and redirect to /products on close
// Remove Postmark API key from source code and put in .env

Key protection and order success

---

src/Components/Cart.js
src/Components/CheckOutModal.js

Cart-responsive

---

src/Components/Login.js
src/Components/newLoginPage.js

// Michael refactored with Formik and Yup
// Yup.email() has known bugs, replaced with regex check
// Added error feedback when log in and sign up attempts fail
// Switched floating labels to fixed labels 
// Fixed back button
// Added mouse-over tips to buttons
// Added redirect for when user logs out as opposed to returning to login screen

Login Validation & Error Handling

---

server/api/users.js
server/db/User.js
server/db/seed.js

// sorted order history api descending on date
// add properly calculated $ amounts to seed file orders

Order History Seed Amounts and Sorted

---

src/Components/ProductReviewCreate.js
src/store/productAll.js
src/store/productSingle.js

/ refactored ProductReviewCreate to not require forceUpdate()
// removed unused code from product store files

Refactor Product Review Create + Cleanup

---

src/Components/Login.js
src/Components/Navbar.js
src/Components/User.js
src/store/auth.js

// Consoilidate logged-in user menu items under single account dropdown
// refactor logout to redirect to home page after logout
// remove order history link from Profile component

feat(front-end): navbar tweaks

---

src/Components/Login.js

fix (front-end): recover login component

---

server/db/seed.js
src/Components/Cart.js
src/Components/CheckOutModal.js
src/Components/Login.js
src/Components/ProductLanding.js
src/Components/User.js
src/store/auth.js
src/store/cart.js

// Empty redux cart on logout
// Commented out references to tax in cart and checkout
// Tweaked login so error message doesn't momentarily display before redirect
// Added jejanov@mac.com as user in seed file

Cart Logout

---

src/Components/Cart.js
src/Components/CheckOutModal.js
src/store/auth.js

added check for items to activate checkout button
cleaned up console logs and unused imports

final clean up on cart
